---
virt_lightning_packages:
  - libguestfs-tools
  - libvirt-bin
  - libvirt-daemon
  - python3
  - python3-libvirt
  - python3-pip
virt_lightning_groups:
  - kvm
  - libvirt
virt_lightning_qemu_owner: libvirt-qemu
virt_lightning_qemu_group: kvm
