---
- name: Install Ansible's virt dependencies
  package:
    name:
      - python-libvirt
      - python-lxml
  become: true
- name: Record the storage pool location
  shell: |
    . ~/venv/bin/activate
    vl storage_dir
  register: storage_dir

- name: Build the images
  shell: |
    . ~/venv/bin/activate
    cd ~/virt-lightning/images
    ./image centos-7 download
  args:
    creates: "{{ storage_dir.stdout }}/upstream/centos-7.qcow2"
