---
- name: Install the virt-lightning dependencies
  package:
    name: "{{ virt_lightning_packages }}"
  become: true
- name: Install git, setup.py needs it
  package:
    name: git
  become: true
- name: Install the dependencies of the virt_net Ansible module
  package:
    name:
      - python-libvirt
      - python-lxml
  become: true
- name: Avoid any conflict with the master network
  command: sed -i s,122,124,g /etc/libvirt/qemu/networks/default.xml
  become: true
- name: Start libvirt
  service:
    name: libvirtd
    state: started
  become: true
- name: Create the virt-lightning network
  virt_net:
    command: define
    name: virt-lightning
    uri: "{{ virt_lightning_qemu_uri }}"
    xml: "{{lookup('file', 'virt-lightning.xml')}}"
  become: true
- name: Start the virt-lightning network
  virt_net:
    command: create
    name: virt-lightning
  become: true
  register: virt_net_start
  failed_when: false
- name: Add the fine users to the current users
  user:
    name: "{{ansible_user_id}}"
    groups: "{{ virt_lightning_groups }}"
  become: true
- name: Write the polkit configuration
  template:
    src: polkit.rules.j2
    dest: /etc/polkit-1/rules.d/80-libvirt.rules
  become: true
  when:
    - ansible_distribution == "Fedora"
    - virt_lightning_qemu_uri == "qemu:///system"
- name: reset ssh connection to reload the groups
  meta: reset_connection
- name: Push the working directory
  synchronize:
    src: ../../virt-lightning
    dest: ~/
  when: dev_mode is defined
- name: Fetch virt-lightning master branch
  git:
    repo: 'https://github.com/virt-lightning/virt-lightning'
    dest: ~/virt-lightning
  when: dev_mode is not defined
- name: Prepare the virtualenv
  shell: |
    python3 -m venv ~/venv
    . ~/venv/bin/activate
    pip install -e ~/virt-lightning
- name: Prepare the configuration directory
  file:
    path: ~/.config/virt-lightning
    state: directory
- name: Write the configuration file
  template:
    src: config.ini.j2
    dest: ~/.config/virt-lightning/config.ini
- name: Create the pool directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ virt_lightning_qemu_owner }}"
    group: "{{ virt_lightning_qemu_group }}"
    mode: "0775"
  with_items:
    - /var/lib/virt-lightning/pool
    - /var/lib/virt-lightning/pool/upstream
  become: true
  when: virt_lightning_qemu_uri == "qemu:///system"
