---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
- name: Disable the update repositories
  command: "dnf config-manager --set-disabled {{ item }}"
  with_items:
    - updates
    - updates-modular
  become: true
  when: ansible_distribution == 'Fedora'
- name: Install
  import_tasks: install.yml
- name: Prepare an image
  import_tasks: image.yml
- name: Test
  import_tasks: test.yml
